### ISSUE TITLE
How to set sampling frequency to 16kHz

### ISSUE THREAD

**Issue by SaraHackett13** [STMicroelectronics-CentralLabs/BlueVoice-for-Linux#6]
I am able to successfully record audio from the STEVAL-BlueMic-1 using the Raspberry Pi 3B+. However, the 16kHz sampling rate results in a lot more noise compared to the 8kHz sampling rate. 

1. I am trying to follow the instructions below and change the sampling frequency in the firmware of STSW-BLUEMIC-1, but in which file do I do this? 
![image](https://user-images.githubusercontent.com/49536808/73106863-111e5700-3ec2-11ea-81bd-0ca33a929cbd.png)

2. If I don't have a Nucleo or SensorTile board, how can I flash my STEVAL-BlueMic-1? 

Thanks.

**Comment by matteoronchi** [comment]
Hi SaraHackett13,

Probably your issue is linked with a bad configuration of the connection interval. To fix this you have to run the following commands on your Raspberry Pi with the right permissions:
```
echo 8 > /sys/kernel/debug/bluetooth/hci0/conn_min_interval
echo 17 > /sys/kernel/debug/bluetooth/hci0/conn_max_interval
```
These allow the right configuration of min and max connection interval parameters.
 
In any case, for other future developments, I suggest you to clone the following repository which is the official one and is currently actively supported:
https://github.com/STMicroelectronics/BlueSTSDK_Python

As you could read in the repository main desciption, the "example_ble_5.py" realize a full BlueVoice over Linux solution.
Rather then the old one, this example implements in addiction:
- Possibility to direct playback your recorded audio and/or to save it into your Raspberry Pi
- Possibility to activate/deactivate a specific beamforming algorithm(*)
- A new and more efficient audio codec, named Opus which will probably become the most used one in the near future (*)
(*) These two features are not compatible with your STEVAL-BlueMic-1, but support a lot of other our boards or development kits.

For further information or more specific demos about this topic, write us.

Have a nice day,
Matteo

**Comment by SaraHackett13** [comment]
Thank you for your help and the extra info! I was able to change the connection interval, and the noise was reduced.
